CREATE TABLE USERT(

	USERNAME VARCHAR(100) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    AUTHORITY VARCHAR(100) NOT NULL
    
)

INSERT INTO USERT VALUES ('guest', '$2a$12$CE46deartnl2hW2BHZaH5.ncw0ZBy5bSLvZEJAS8Dyvpj8TPcilY2', TRUE,'GUEST');
INSERT INTO USERT VALUES ('admin', '$2a$12$CE46deartnl2hW2BHZaH5.ncw0ZBy5bSLvZEJAS8Dyvpj8TPcilY2', TRUE,'ADMIN');

SELECT * FROM USERT


CREATE TABLE USERBOARD(
	BOARDSEQ INT(1) PRIMARY KEY AUTO_INCREMENT,
 	USERNAME  VARCHAR(100) NOT NULL,
 	TITLE VARCHAR(500) NOT NULL,
 	CONTENT VARCHAR(1000) NOT NULL,
 	CONSTRAINT FK_USERBOARD_USERNAME FOREIGN KEY(USERNAME) REFERENCES USERT(USERNAME)
);


SELECT * FROM USERBOARD;

DROP TABLE USERT;
DROP TABLE USERBOARD;

CREATE TABLE SEQTEST(
	SEQ INT(1) PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL
);

INSERT INTO SEQTEST(NAME) VALUES('조');
INSERT INTO SEQTEST(NAME) VALUES('수');
INSERT INTO SEQTEST(NAME) VALUES('민');

SELECT * FROM SEQTEST;