CREATE TABLE USERS (
    USERNAME VARCHAR2(100) PRIMARY KEY,
    PASSWORD VARCHAR2(100) NOT NULL,
    ENABLED CHAR(1) CONSTRAINT booleantest_verfieid_ck CHECK(ENABLED = '0' OR ENABLED = '1')
	);

CREATE TABLE AUTHORITIES (
    USERNAME  VARCHAR2(100) NOT NULL,
    AUTHORITY VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    CONSTRAINT UK_AUTHORITIES UNIQUE (USERNAME, AUTHORITY)
	);

INSERT INTO USERS VALUES ('guest', '$2a$12$CE46deartnl2hW2BHZaH5.ncw0ZBy5bSLvZEJAS8Dyvpj8TPcilY2', 1);
INSERT INTO AUTHORITIES VALUES ('guest', 'GUEST');
INSERT INTO USERS VALUES ('admin', '$2a$12$CE46deartnl2hW2BHZaH5.ncw0ZBy5bSLvZEJAS8Dyvpj8TPcilY2', 1);
INSERT INTO AUTHORITIES VALUES ('admin', 'ADMIN');
INSERT INTO AUTHORITIES VALUES ('asd', 'ADMIN');

SELECT * FROM USERS
SELECT * FROM AUTHORITIES

DROP TABLE USERS;
DROP TABLE AUTHORITIES;

DELETE FROM USERS WHERE USERNAME = 'asd';
DELETE FROM AUTHORITIES WHERE USERNAME = 'asd';

CREATE TABLE USERT(

	USERNAME VARCHAR2(100) PRIMARY KEY,
    PASSWORD VARCHAR2(100) NOT NULL,
    ENABLED CHAR(1) CONSTRAINT booleantest_verfieid_ck2 CHECK(ENABLED = '0' OR ENABLED = '1'),
    AUTHORITY VARCHAR2(100) NOT NULL
    
)

INSERT INTO USERT VALUES ('guest', '$2a$12$CE46deartnl2hW2BHZaH5.ncw0ZBy5bSLvZEJAS8Dyvpj8TPcilY2', 1,'GUEST');
INSERT INTO USERT VALUES ('admin', '$2a$12$CE46deartnl2hW2BHZaH5.ncw0ZBy5bSLvZEJAS8Dyvpj8TPcilY2', 1,'ADMIN');

SELECT * FROM USERT